---
kind: pipeline

steps:
- name: build
  privileged: true
  image: rancher/dapper:1.11.2
  volumes:
  - name: docker
    path: /var/run/docker.sock
  commands:
  - dapper ci

- name: github-binary-publish-release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "bin/kontainer-engine-driver-aliyun-*"
  when:
    branch: master
    event: tag
    ref:
      exclude: [ refs/tags/*rc* ]

- name: github-binary-publish-prerelease
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    checksum:
    - sha256
    files:
    - "bin/kontainer-engine-driver-aliyun-*"
    prerelease: true
  when:
    branch: master
    event: tag
    ref:
      include: [ refs/tags/*rc* ]

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

node:
  instance: agent-amd64
